# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(337, 378)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 20, 258, 287))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.todoListView = QtWidgets.QListView(self.widget)
        self.todoListView.setObjectName("todoListView")
        self.gridLayout.addWidget(self.todoListView, 0, 0, 1, 2)
        self.completePushButton = QtWidgets.QPushButton(self.widget)
        self.completePushButton.setObjectName("completePushButton")
        self.gridLayout.addWidget(self.completePushButton, 2, 1, 1, 1)
        self.deletePushButton = QtWidgets.QPushButton(self.widget)
        self.deletePushButton.setObjectName("deletePushButton")
        self.gridLayout.addWidget(self.deletePushButton, 2, 0, 1, 1)
        self.addPushButton = QtWidgets.QPushButton(self.widget)
        self.addPushButton.setObjectName("addPushButton")
        self.gridLayout.addWidget(self.addPushButton, 3, 0, 1, 2)
        self.todoLineEdit = QtWidgets.QLineEdit(self.widget)
        self.todoLineEdit.setObjectName("todoLineEdit")
        self.gridLayout.addWidget(self.todoLineEdit, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 337, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.completePushButton.setText(_translate("MainWindow", "Complete"))
        self.deletePushButton.setText(_translate("MainWindow", "delete"))
        self.addPushButton.setText(_translate("MainWindow", "Add"))
