# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 340)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SubmitButton = QtWidgets.QPushButton(self.centralwidget)
        self.SubmitButton.setGeometry(QtCore.QRect(80, 130, 83, 25))
        self.SubmitButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.SubmitButton.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/files/icons/icons/blog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SubmitButton.setIcon(icon)
        self.SubmitButton.setFlat(False)
        self.SubmitButton.setObjectName("SubmitButton")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(10, 20, 62, 17))
        self.nameLabel.setObjectName("nameLabel")
        self.lastNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.lastNameLabel.setGeometry(QtCore.QRect(10, 50, 151, 17))
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.birhtDayLabel = QtWidgets.QLabel(self.centralwidget)
        self.birhtDayLabel.setGeometry(QtCore.QRect(10, 80, 101, 17))
        self.birhtDayLabel.setObjectName("birhtDayLabel")
        self.birthDayLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.birthDayLineEdit.setGeometry(QtCore.QRect(120, 80, 113, 25))
        self.birthDayLineEdit.setDragEnabled(False)
        self.birthDayLineEdit.setObjectName("birthDayLineEdit")
        self.nameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLineEdit.setGeometry(QtCore.QRect(120, 20, 113, 25))
        self.nameLineEdit.setText("")
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.lastNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lastNameLineEdit.setGeometry(QtCore.QRect(120, 50, 113, 25))
        self.lastNameLineEdit.setObjectName("lastNameLineEdit")
        self.informationTextBrowser = TextBrowser(self.centralwidget)
        self.informationTextBrowser.setGeometry(QtCore.QRect(280, 20, 256, 192))
        self.informationTextBrowser.setReadOnly(True)
        self.informationTextBrowser.setObjectName("informationTextBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 22))
        self.menubar.setObjectName("menubar")
        self.menumenu = QtWidgets.QMenu(self.menubar)
        self.menumenu.setObjectName("menumenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.submitAction = QtWidgets.QAction(MainWindow)
        self.submitAction.setIcon(icon)
        self.submitAction.setObjectName("submitAction")
        self.menumenu.addAction(self.submitAction)
        self.menubar.addAction(self.menumenu.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.submitAction)

        self.retranslateUi(MainWindow)
        self.SubmitButton.clicked.connect(self.informationTextBrowser.clear) # type: ignore
        self.SubmitButton.clicked.connect(MainWindow.submitInformation) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SubmitButton.setToolTip(_translate("MainWindow", "submits your information"))
        self.SubmitButton.setStatusTip(_translate("MainWindow", "submits your information"))
        self.SubmitButton.setWhatsThis(_translate("MainWindow", "submits your information"))
        self.SubmitButton.setText(_translate("MainWindow", "Submit"))
        self.nameLabel.setText(_translate("MainWindow", "name"))
        self.lastNameLabel.setText(_translate("MainWindow", "Last Name"))
        self.birhtDayLabel.setText(_translate("MainWindow", "Birth Day"))
        self.birthDayLineEdit.setInputMask(_translate("MainWindow", "0000/00/00;_"))
        self.menumenu.setTitle(_translate("MainWindow", "menu"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.submitAction.setText(_translate("MainWindow", "Submit"))

from .textbrowser import TextBrowser
